### ISSUE TITLE
Make a decision on keeping Gatsby vs. just starting over with React

### ISSUE THREAD

**Issue by hjawad22** [OutBoulderCounty/icc-ui#18]
This is a really good video I found by the founder of Gatsby to get a better understanding of it. 
[Video](https://www.youtube.com/watch?v=MZLS4cq7fRY)

Benefits of Gatsby:

- Faster websites due to the preloading of data before an action for it to be retrieved is made by the user.  

- Uses GraphQL to easily access any data from the API.

Cons of Gatsby:

- Learning curve, uses react but in a slightly different way.
- GraphQL learning curve if you don't already know it.

**Comment by DanielekPark** [comment]
@hjawad22 
If we chose to start over, I think the modern day standard is to use a React based framework. 

https://react.dev/learn/start-a-new-react-project
