### ISSUE TITLE
Create a PR template

### ISSUE THREAD

**Issue by hjawad22** [OutBoulderCounty/icc-ui#20]

**Comment by DanielekPark** [comment]
@colehart @hjawad22 what do you think?

Repo should be already cloned

1. git pull
2. git checkout develop 
3. git checkout -b (newBranch)
4. git status
5. git add (file that was changed)
6. git status			
7. git commit -m ”brief description on feature/bug fix”
8. git push -u origin fix-header
(Go to GitHub  link for pull request, link should be provided in the terminal when a commit is pushed)
9. git fetch upstream (if there was an error)

**Comment by hjawad22** [comment]
@DanielekPark Thanks Daniel this looks like a good start! I also have used this one in the past and it has been helpful. Maybe we can make a new one with a combination of the two? 

## Types of changes made?

- [ ]  testing
- [ ] documentation
- [ ] functionality

## What does this PR do?

- [ ] Adds functionality

- [ ] Updates JS for

- [ ] Fixes bug for

## Relevant Tickets?

- [ ] Finishes iteration or ticket for

## Questions/Comments/Relevant Screenshots?

**Comment by DanielekPark** [comment]
@hjawad22 sure that looks good
